dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: opentest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- name: opentest-go
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: playback-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: subtitle-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
